version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - python -V
      - aws --version
      - npm i -g serverless
      - sls --version
  pre_build:
    commands:
      - sls deploy -v -s test
      - ls -l
      - chmod 755 run-test.sh
      - ls -l
      - ./run-test.sh
      - sls remove -v -s test
      - echo Clean sls stack in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - sls deploy -v -s dev
  post_build:
    commands:
      - echo Build completed on `date`
