version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - python -V
      - aws --version
      - docker --version
      - npm i -g serverless
      - sls --version
      - npm i
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - python -m unittest tests/test_hello.py
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - pwd
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then echo Build completed on `date`; echo Starting deployment; sls deploy -v -s dev; chmod 755 run-test.sh; ls -l; ./run-test.sh; else echo Build failed ignoring deployment; fi
