service: eltest

frameworkVersion: '2'
plugins:
  - serverless-python-requirements

custom:
  deletionPolicy: Retain
  yamlStage: ${opt:stage, 'dev'}

package:
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - .pytest_cache/**
    - eltest_manifest.json


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-central-1
  stage: ${self:custom.yamlStage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - "*"

  environment:
    MY_BUCKET: eltest-${opt:stage, 'dev'}


functions:
  hello:
    handler: controllers/hello.handler
    events:
      - http:
          path: /hello
          method: get

  initQuickSight:
    handler: functions/initFunc.handler


resources:
  Resources:

    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.MY_BUCKET}

    PutManifestToS3Resource:
      Type: Custom::PutManifestToS3Resource
      DependsOn: MyBucket
      Properties:
        ServiceToken:
          Fn::GetAtt: [InitQuickSightLambdaFunction, Arn]
        Bucket: ${self:provider.environment.MY_BUCKET}
