service: eltest

frameworkVersion: '2'
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
  deletionPolicy: Retain
  yamlStage: ${opt:stage, 'dev'}


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-central-1
  stage: ${self:custom.yamlStage}

  iamRoleStatements:
#    - Effect: Allow
#      Action:
#        - states:StartExecution
#        - states:DescribeExecution
#        - states:ListExecutions
#      Resource:
#        - "*"

  environment:


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
