service: eltest

frameworkVersion: '2'
plugins:
  - serverless-python-requirements

custom:
  deletionPolicy: Retain
  yamlStage: ${opt:stage, 'dev'}

package:
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - .pytest_cache/**


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-central-1
  stage: ${self:custom.yamlStage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - "*"

  environment:
    MY_BUCKET: eltest


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
