service: eltest

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  environment:
    API_URL:
      !Join
      - ''
      - - 'https://'
        - !Ref ApiGatewayRestApi
        - '.execute-api.'
        - ${opt:region, self:provider.region}
        - '.amazonaws.com/'
        - ${opt:stage, self:provider.stage}


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
