service: eltest

frameworkVersion: '2'
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"


  deletionPolicy: Retain
  yamlStage: ${opt:stage, 'dev'}

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-central-1
  stage: ${self:custom.yamlStage}

  iamRoleStatements:
#    - Effect: Allow
#      Action:
#        - states:StartExecution
#        - states:DescribeExecution
#        - states:ListExecutions
#      Resource:
#        - "*"

  environment:


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
